name: Garage CI

env:
  GARAGE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TRAVIS_COMMIT_RANGE: ${{ github.base_ref }}...${{ github.head_ref }}
  DOCKER_TAG: garage-ci-${{ github.run_id }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_docker_container:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    # Not enough disk space to pull and build :-/
    # - name: Pull from cache (GitHub Package Registry)
    #   run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/ci-docker-cache
    - name: Build Docker container
      run: |
        docker build . \
          -f docker/Dockerfile.ci \
          -t "${DOCKER_TAG}" \
          --build-arg GARAGE_GH_TOKEN \
          --cache-from="docker.pkg.github.com/${GITHUB_REPOSITORY}/${DOCKER_TAG}"
    - name: Push to cache (GitHub Package Registry)
      run: |
        docker tag "${DOCKER_TAG}" "docker.pkg.github.com/${GITHUB_REPOSITORY}/${DOCKER_TAG}"
        docker push "docker.pkg.github.com/${GITHUB_REPOSITORY}/${DOCKER_TAG}"


  check_pre_commit:
    runs-on: ubuntu-latest
    needs: build_docker_container

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      run: docker pull "docker.pkg.github.com/${GITHUB_REPOSITORY}/${DOCKER_TAG}"
    - name: Rename docker image
      run: docker tag docker.pkg.github.com/${GITHUB_REPOSITORY}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: Check pre-commit
      run: |
        docker run \
          -e TRAVIS_COMMIT_RANGE \
          --memory 7500m \
          --memory-swap 7500m \
          "${DOCKER_TAG}" scripts/travisci/check_precommit.sh
